from random import randint, choice
import time

from .restriction_base import RestrictionBase
from ..manager.hotkey_manager import HotkeyManager
from ..utils.constants import Constants


class AutoChat(RestrictionBase):
    title = "Auto chat!"
    difficulty = 2
    attributes = [Constants.CHAT, Constants.AUTO]

    delay = 0

    messages = [
        "GG, our bot lane is a joke.",
        "These junglers are so useless. Did they forget they have a minimap?",
        "Top lane has fed again. Can we please get a better split pusher?",
        "Mid lane has zero map awareness. Does anyone have a GPS for them?",
        "Seriously, do we have a jungler or just a glorified campfire in the jungle?",
        "Can someone please explain to our ADC that farming is not an optional activity?",
        "I'm starting to think our team composition was generated by a monkey hitting random keys.",
        "Is our support allergic to wards or just allergic to winning?",
        "I've seen better rotations at a slow dance competition.",
        "Our team synergy is about as existent as my father.",
        "Great, our jungler decided to AFK farm while the enemy team takes all objectives.",
        "Is our mid laner playing blindfolded or just pretending to be useless?",
        "Our top laner must be sponsored by the enemy team with all that feeding.",
        "Do we have a support or a walking ward dispenser?",
        "I've seen better engages from a group of blindfolded toddlers.",
        "It's like our team is allergic to teamwork.",
        "Our ADC must have a secret mission to see how many deaths they can accumulate.",
        "Does anyone on our team know what an objective is?",
        "I've seen more map awareness from a minion.",
        "Our team coordination is about as organized as a pack of wild animals.",
        "Can someone please remind our top laner that towers are not decorative pieces?",
        "Our team fights are like watching a train wreck in slow motion.",
        "I've had more successful ganks in bot games than with this jungler.",
        "Is our mid laner typing an essay or actually playing the game?",
        "Our team's decision-making skills are on par with a coin flip.",
        "Is our ADC using a rock to control their champion?",
        "Has our jungler forgotten their smite key?",
        "Did our support accidentally bind their abilities to the emote wheel?",
        "I've seen better teamwork in a game of solitaire.",
        "Our mid laner must be cosplaying as a turret with all that immobility.",
        "Our ADC's positioning is so bad, they must be trying to set a world record for most deaths.",
        "Does our jungler think dragon and Baron are on vacation?",
        "Our support is like a black hole for vision.",
        "Our top laner's teleport plays are more predictable than the weather forecast.",
        "Our team's map control is about as effective as yelling directions into a void.",
        "Did our mid laner's champion get nerfed mid-game or are they just inting?",
        "Our bot lane's communication is so bad, they must be using smoke signals.",
        "Is our jungler allergic to ganking or just allergic to winning?",
        "Our team's coordination is like trying to herd cats.",
        "Is our top laner playing with a trackpad?",
        "Our ADC must be sponsored by the enemy team with all those donations.",
        "Is our mid laner playing with a blindfold or just not paying attention?",
        "Our team's rotations are like watching a merry-go-round.",
        "Did our jungler mistake the enemy team for their own?",
        "Our support must have a ward phobia.",
        "Is our top laner allergic to minions or just allergic to gold?",
        "Our team's shot calling is like listening to a broken record.",
        "Our ADC must have a part-time job as a minion with all that farming.",
        "Is our mid laner waiting for an invitation to join the teamfight?",
        "Our team's vision control is like playing hide and seek with toddlers.",
        "Did our support leave their warding trinket at home?",
        "Our jungler's pathing is so predictable, even the enemy wards are yawning.",
        "Is our top laner intentionally feeding or just having a bad game?",
        "Our team's objective control is like trying to herd cats.",
        "Is our ADC playing with their screen turned off?",
        "Our mid laner's map awareness is about as sharp as a marble.",
        "Our support's itemization is like trying to build a sandcastle in a tsunami.",
        "Did our top laner forget to buy items?",
        "Our team's rotations are like watching a turtle race.",
        "Is our mid laner playing with one hand?",
        "Our ADC's positioning is so bad, they must be moonlighting as a melee champion.",
        "Our team's macro play is about as coherent as a toddler's bedtime story.",
        "Is our support warding with a blindfold on?",
        "Our top laner's CS is so low, they must think minions are optional.",
        "Is our mid laner playing on a toaster?",
        "Our team's decision-making is like a roulette wheel with all bad outcomes.",
    ]

    @classmethod
    def init(cls):
        cls.remaining_messages = cls.messages.copy()

    @classmethod
    def restriction_content(cls):
        if time.time() < cls.delay:
            pass
        elif randint(1, int(25000 / cls.interval)) == 1:
            if len(cls.remaining_messages) <= 0:
                cls.remaining_messages = cls.messages.copy()

            rand_message = randint(0, len(cls.remaining_messages) - 1)
            message = cls.remaining_messages.pop(rand_message)
            HotkeyManager.write_chat(message)
            cls.delay = time.time() + 15
